apiVersion: v2
name: guestbook-basic
version: 0.1.0
appVersion: v4
description: A chart for deploying the Guestbook tutorial application, including a PHP frontend and a Redis backend
keywords:
  - guestbook
