## guestbookReplicas specifies the number of Guestbook pods to deploy
guestbookReplicas: 3
## image sets the image to use of the Guestbook application
image:
  registry: gcr.io
  repository: google-samples/gb-frontend
  tag: v4
## resources specifies the resource requests and limits of a Guestbook pod
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi
healthchecks:
  ## healthchecks.enabled determines whether to include a pre-configured liveness and readiness probe
  enabled: true
  ## healthchecks.port determines the port to use against the healthchecks
  port: 80
## enableBackup determines whether the Redis database should be backed up on a helm upgrade
enableBackups: true
## enableRestore determines whether the Redis database should be restored on a helm rollback
enableRestores: true
## serviceType can be set to ClusterIP, NodePort, or LoadBalancer
serviceType: NodePort
## servicePorts determines the ports that should exposed on the service
servicePorts:
  - 80

redis:
  ## set to false because the Guestbook app does not support auth
  usePassword: false
  ## disable aof persistence
  configmap: |-
    appendonly no
    save ""
  master:
    persistence:
      size: 1Gi
  slave:
    persistence:
      size: 1Gi
