## guestbookReplicas specifies the number of Guestbook pods to deploy
guestbookReplicas: 3
## resources specifies the resource requests and limits of a Guestbook pod
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

redis:
  ## set to false because the Guestbook app does not support auth
  usePassword: false
  ## disable aof persistence
  configmap: |-
    appendonly no
    save ""
