apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
spec:
  type: NodePort 
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}
