apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
    "app.kubernetes.io/component": frontend
spec:
  type: {{ .Values.serviceType }}
  ports:
{{- range .Values.servicePorts }}
  - port: {{ . }}
{{- end }}
  selector:
    app: {{ .Release.Name }}
