apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-slave
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-slave
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-slave
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: {{ .Release.Name }}-redis-master
        ports:
        - containerPort: 6379
