apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-master
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: {{ .Release.Name }}-redis-master
