apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
spec:
{{- $serviceTypes := list "ClusterIP" "NodePort" "LoadBalancer" }}
{{- if has .Values.serviceType $serviceTypes }}
  type: {{ .Values.serviceType }}
{{- else }}
  {{- fail "value 'serviceType' must be either 'ClusterIP', 'NodePort', or 'LoadBalancer'" }}
{{- end }}
  ports:
{{- range .Values.servicePorts }}
  - port: {{ . }}
{{- end }}
  selector:
    app: {{ .Release.Name }}