apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-backup
  labels:
{{ include "guestbook.common-labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
        - name: backup
          image: redis:alpine3.11
          command: ["/bin/sh", "-c"]
          args: ["redis-cli -h {{ .Release.Name }}-redis-master save && cp /data/dump.rdb /backup/dump.rdb"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-{{ .Release.Name }}-redis-master-0
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-backup-{{ sub .Release.Revision 1 }}
            